@extends('layouts.app')

@section('content')

	<section class="about-banner">

		<div class="container">

			<h4>Security</h4>

<p><a href="{!! url('/') !!}">Home</a>

<a href="">/</a>

<a href="#">Security</a> </p>



	</section>

	<div class="clearfix"></div>

	<section class="security-content">

		<div class="container">

			<div class="row">

				<div class="col-sm-12">	

					

					<div class="col-sm-9 security-inner">

					<h4>Most of your bitcoins in your PerfektPay wallet are stored offline</h4>

					<img src="images/line.png">

						   <p>Imagine a world without internet. Yes, without internet everything seems so dead. But perfekt Pay brings your offline zone back to life. Technically, the set of multiple addresses for offline storage are generated on a computer that has never and never will be connected to the internet. This method actually helps as a crucial security measure against theft, loss and hacking. The address-private key pairs obtained are encrypted using AES-256, sealed in envelopes and stored in multiple safe deposit lockers. The AES-256 keys are also stored in multiple safe deposit lockers at different locations. The reason- In the unlikely event of a security compromise at any one of the locations, your bitcoins remain safe.</p>

						   



							<p>Our server automatically chooses the next offline address once a max threshold is reached on a particular address. This way, if any of the addresses are compromised due to circumstances beyond our control, the rest of the address remain secure. Hence, through perfekt Pay majority of your bitcoin purchases are offline and in very secured hands.</p>



					</div>

				

					<div class="col-sm-3 security-right">

						<img src="images/security-phone.png">

					</div>

					</div>

					</div>

				

					</div>

					<section class="grey-inner">

					<div class="container">

					<div class="row">

					<div class="col-sm-12">

					<div class="col-sm-9">

					 <ul class="nav nav-tabs">

					<li class="active"><a data-toggle="tab" href="#home"><p>Authenticate via<br>Google</p>

					<img src="images/1.png"></a></li>

					<li><a data-toggle="tab" href="#menu1"><p>Signing-in<br>Verification</p><img src="images/2.png"> </a></li>

					<li><a data-toggle="tab" href="#menu2"><p>Secure your <br>Buying/Selling</p><img src="images/3.png"></a></li>

				  </ul>

						</div>

						

					<div class="col-sm-12">

						<div class="tab-content">

					<div id="home" class="tab-pane fade in active">

					  <p>Once you are done with verification of your account, you can set up “Double Authentication” using the google authenticator. For the same, you can click on “2 Factor Auth” link which can be found under Account > Settings menu. You need your registered mobile phone number to generate a unique 6 digit code to login and spend the funds. Google authenticator is available for android, IOS devices and blackberry devices. To install google authenticator on your mobile visit <a href="">https://support.google.com/accounts/answer/1066447?hl=en.</a></p>

					</div>

					<div id="menu1" class="tab-pane fade">

					  <p>After the activation of Google Authenticator for your profile, whenever you try to sign-in, perfekt Pay server checks if you have the two factor authentication enabled and then displays an extra text box to key in your authentication code (generated by google authenticator). This process adds up another security to your profile.</p>

	

					</div>

					<div id="menu2" class="tab-pane fade">

					  <p>With the help of Google Authenticator, You can also limit your transfer BTC limit through google authenticator. This means - If your account threshold is 5 BTC, you will not be able to send/withdraw more than 5 BTC with in the 24 hours even using multiple withdrawal attempts unless using the google authenticator. Hence, an extra step can take you very closer to tight, safe and secured transaction. With perfekt pay, every transaction counts which is fully packed with security and provisions of extra safety on all ends.</p>

					</div>

				   

				  </div>

					</div>

					</div>

					</div>

					</div>

					</section>

					</section>

		

	<section class="security-content" style="padding-bottom:40px; color:hsl(209, 95%, 17%); text-align:justify;">

	<div class="container">

	<div class="row">

	<div class="col-sm-12 security-inner" style="padding-bottom:0;">

	<h4>Bitcoin Boom Cycles</h4>

	<img src="images/line.png">

	</div>

	<div class="col-sm-4 recomend">

	<div class="col-md-2 col-sm-3"><img src="images/icons.png"></div>

	<div class="col-md-10 col-sm-9"><h4>Google Authenticator</h4>

	<p>Authenticate Your Account</p>

	<p>Enable 2 factor authentication for PerfektPay account. Do not reveal the google authenticator string. To enable 2 factor authentication in PerfektPay, go to security >> 2 factor Auth.</p></div>

	</div>

	<div class="col-sm-4 recomend">

	<div class="col-md-2 col-sm-3"><img src="images/icons.png"></div>

	<div class="col-md-10 col-sm-9"><h4>Password</h4>

	<p>Keep Different Passwords</p>

	<p>It is recommended that the Primary password used for accessing PerfektPay account is not same as the password(s) of your personal email accounts.</p></div>

	</div>

	

	<div class="col-sm-4 recomend">

	<div class="col-md-2 col-sm-3"><img src="images/icons.png"></div>

	<div class="col-md-10 col-sm-9"><h4>Secure https:\\</h4>

	<p>‘S’ for Security</p>

	<p>Make sure you always use HTTPS while accessing your PerfektPay account(https://www.perfektpay.com). This ensures the privacy and integrity of the exchanged data.</p></div>

	</div>

	

	<div class="col-sm-4 recomend">

	<div class="col-md-2 col-sm-3"><img src="images/icons.png"></div>

	<div class="col-md-10 col-sm-9"><h4>Virus https:\\</h4>

	<p>Protect yourself from Virus</p>

	<p>Do not open your mail or other links while your PerfektPay account is open. Clicking on a malicious link might lead to browser compromise, which might in turn lead to the compromise of your PerfektPay account. This may lead to the loss of your BTC. Use a different browser instead.</p></div>

	</div>

	

	<div class="col-sm-4 recomend">

	<div class="col-md-2 col-sm-3"><img src="images/icons.png"></div>

	<div class="col-md-10 col-sm-9"><h4>Complex Passwords</h4>

	<p>Unique Password</p>

	<p>Make sure to use a complex password. To create a complex password, you can use combinations of alphabets(Upper/Lower case), numericals, special characters and is atleast 8 characters long.</p></div>

	</div>

	

	<div class="col-sm-4 recomend">

	<div class="col-md-2 col-sm-3"><img src="images/icons.png"></div>

	<div class="col-md-10 col-sm-9"><h4>Paper Wallet</h4>

	<p>More Security with Paper Wallet</p>

	<p>Paper wallet is preferred to save your Bitcoin. Do not save your Bitcoin on computers, mobile phones or email/drives. To generate paper wallet go to Security >> Paper Wallet.</p></div>

	</div>

	</div>

	</div>

	</section>

@stop