@extends('user.layouts.layout')
@section('content')
<link rel="stylesheet" href="assets/stylesheets/support.css">

<style>
    .row.top-bar-inner {
  display: none;
}
.content-body{
    MARGIN-TOP:60PX;
}
</style>
<div class="inner-wrapper">
	<section role="main" class="content-body">		
	<div class="container">
		<div class="row">
			<div class="col-sm-12">
				<div id="breadcrumbs">
					<a href="{{url('/')}}">Home</a>
					›
					<a href="how-to-create-account">Creating an Perfektpay Account</a>
					>
					<a href="verification">What is Perfektpay's Verification </a>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-sm-8">
				<div id="support-main">
						<div class="support-body">
							<div class="content article">
								<div class="title">
								<h3>What is Perfektpay's Verification Process?</h3>
								<div class="meta">Last Updated: Mar 05, 2018 12:54PM UTC</div>
								</div>
								<div class="article-content">
								<p style="text-align: justify;" dir="ltr">
							<span style="font-size:14px;">
							<span style="font-family:arial,helvetica,sans-serif;">
							<span class="s1">At Perfektpay, we have implemented an account verification process which differs slightly by region. </span>
							<br>
							<br>
							<span class="s1">
							<b>US Customers</b>
							<br>
							<br>
							For US-based prospective accounts who wish to sign up with us as either an individual or institutional account, we have implemented a knowledge-based authentication system (KBA) to enhance our account verification process. You may have to answer several questions generated by the system based on your identity information such as name, address and Social Security number.
							</span>
							</span>
							</span>
							</p><br>
							<p class="p2"> </p>
								<p class="p1">
								<span style="font-size:14px;">
								<span style="font-family:arial,helvetica,sans-serif;">
								<span class="s1">The powerful KBA system allows a speedy on-boarding process. You can be successfully verified and start trading with us immediately. Your account may be under review if the KBA system is not able to verify your identity. You may be requested to submit additional identification documents to us to proceed with the account verification process. This process could take approximately 1 to 3 business days to be completed.</span>
								</span>
								</span>
								</p>
								<p class="p3">
								<span style="font-size:14px;">
								<span style="font-family:arial,helvetica,sans-serif;">
								<span class="s1"> </span>
								</span>
								</span>
								</p>
								<p class="p1">
								<span style="font-size:14px;">
								<span style="font-family:arial,helvetica,sans-serif;">
								<span class="s1">
								Institutional investors are also required to submit proof of beneficial owners' identification and residence* as well as requisite
								<a href="required-documents">
								<span class="s3">corporate documents</span>
								</a>
								for account verification purposes upon signing up.
								</span>
								</span>
								</span>
								<br><br>
								</p>
								<p class="p3">
								<span style="font-size:14px;">
								<span style="font-family:arial,helvetica,sans-serif;">
								<span class="s1">
								<b>Non-US Customers</b>
								</span>
								</span>
								</span>
								</p><br>
								<p class="p2"> </p>
								<p class="p4">
								<span style="font-size:14px;">
								<span style="font-family:arial,helvetica,sans-serif;">
								<span class="s1">For prospects based prospective accounts outside of the US, the primary account holder must submit to us a photo identity document (i.e. identity card, driving license or passport) and proof of residence (i.e. utility bill) within the past 6 months for account verification purposes. This process could take approximately 1 to 3 business days to be completed.</span>
								</span>
								</span>
								</p>
								<p class="p1">
								<br>
								<span style="font-size:14px;">
								<span style="font-family:arial,helvetica,sans-serif;">
								<span class="s1">
								Institutional investors are also required to submit proof of beneficial owners' identification and residence* as well as requisite
								<a href="required-documents">
								<span class="s3">corporate documents</span>
								</a>
								for account verification purposes upon signing up.
								</span>
								<br>
								<br>
								<span class="s4">
								<i>*Perfektpay only requires beneficial owners that own 25% or more in the company to submit proof of identification and residence</i>
								</span>
								</span>
								</span>
								</p>
								</div>
								<div id="rate_article_container" style="">
								<div id="rate_article">
								<div>
								<a class="rate_link" rel="nofollow" data-remote="true" data-method="post" href=""> Yes </a>
								<span> I found this article helpful </span>
								</div>
								<div class="rate-link-down">
								<a class="rate_link" rel="nofollow" data-remote="true" data-method="post" href=""> No</a>
								<span> I did not find this article helpful </span>
								</div>
								</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			
               <div class="col-sm-4">
    					<div id="support-side">
    						<div class="content">
    							<h3>Contact Us</h3>
    							<ul>
    								<li> </li>
    								<li>
    									<a href="">Email Us</a>
    								</li>
    								<li> Questions? Please contact us at help@Perfektpay.com. </li>
    							</ul>
    						</div>
    						<br>
    						<a class="why_itbit" href="trading"> Back to Perfektpay Trading Services </a>
    					</div>
    				</div>
    			</div>
    		</div>
    	</section>
    </div>
@stop	